name: data_eng_gold
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.11.0"
profile: data_eng
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

flags:
  send_anonymous_usage_stats: false

models:
  data_eng_gold:
    +persist_docs:
      relation: true
      columns: true
    silver:
      +materialized: view
    gold:
      +materialized: table
