"""Download Météo France climatologie data from data.gouv.fr.

Downloads hourly climatology data for all 95 metropolitan French departments.
Uses the data.gouv.fr API to discover resources and prefers Parquet files
(auto-generated by Hydra, ~20x smaller) when available, falling back to CSV.gz.
If the API is unreachable, falls back to hardcoded CSV.gz URLs.

Hydra auto-converts large CSV.gz files into Parquet
(threshold configured server-side by data.gouv.fr — see Hydra source for current value).
Parquet availability per department depends on this threshold and may change over time.

The per-department files are normalized to a uniform all-Utf8 schema and merged into a
single Parquet via lazy scanning.
"""

import re
import shutil
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TypedDict

import httpx
import polars as pl
from tqdm import tqdm

from data_eng_etl_electricity_meteo.core.exceptions import DownloadStageError
from data_eng_etl_electricity_meteo.core.logger import get_logger
from data_eng_etl_electricity_meteo.core.settings import settings
from data_eng_etl_electricity_meteo.utils.progress import (
    BatchProgressFactory,
    DownloadProgressReporter,
)

logger = get_logger("dl.meteo_clim")

# data.gouv.fr API for the Météo France HOR (hourly) dataset
# Resources endpoint requires API v2 (v1 returns 405 on /resources/)
DATAGOUV_METEO_FRANCE_CLIMATOLOGIE_HOR_DATASET_ID = "6569b4473bedf2e7abad3b72"
_RESOURCES_API_URL = (
    "https://www.data.gouv.fr/api/2/datasets/"
    f"{DATAGOUV_METEO_FRANCE_CLIMATOLOGIE_HOR_DATASET_ID}/resources/"
)

# Direct download base URL (used for CSV.gz fallback when API is unavailable)
_BASE_URL = "https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/HOR"

# Metropolitan France departments: 01-19, 20 (Corse), 21-95 (95 total)
# data.gouv.fr uses "20" for Corse — "2A"/"2B" files do not exist (HTTP 404)
DEPARTMENTS: frozenset[str] = frozenset(
    {
        *{f"{i:02d}" for i in range(1, 20)},
        "20",
        *{f"{i:02d}" for i in range(21, 96)},
    }
)

# Landing output filename
_MERGED_FILENAME = "merged.parquet"

# Columns retained at download time (aligned with BRONZE_COLUMNS in
# meteo_france_climatologie.py). Pruning 196 → 16 columns here avoids
# OOM during the merge of 95 per-department parquets (~9 GB → ~760 MB).
_LANDING_COLUMNS = [
    "NUM_POSTE",
    "AAAAMMJJHH",
    "GLO",
    "INS",
    "N",
    "FF",
    "DD",
    "FXI",
    "T",
    "TX",
    "TN",
    "TD",
    "U",
    "RR1",
    "PSTAT",
    "PMER",
]

_TITLE_RE = re.compile(r"HOR_departement_(\w+)_periode_(\d{4})-(\d{4})")
_API_PAGE_SIZE = 50
_DOWNLOAD_MAX_WORKERS = 8


class DepartmentResource(TypedDict):
    """Download URLs for a single department."""

    dept: str
    csv_url: str
    parquet_url: str | None


# --------------------------------------------------------------------------------------
# Resource discovery
# --------------------------------------------------------------------------------------


def _fetch_department_resources(
    *,
    client: httpx.Client,
    year_start: int,
    year_end: int,
) -> dict[str, DepartmentResource]:
    """Discover department resources via the data.gouv.fr API.

    Queries the dataset resources endpoint, filters by period and department, and
    returns download URLs (CSV.gz + optional Parquet Hydra).

    The result may be partial (not all 95 departments). The caller is responsible for
    supplementing with fallback URLs for missing departments.

    Parameters
    ----------
    client
        HTTP client for API requests.
    year_start
        Start year of the period.
    year_end
        End year of the period.

    Returns
    -------
    dict[str, DepartmentResource]
        Mapping ``dept → resource`` for departments found via the API.
        May be empty if the API returns no matching resources.

    Raises
    ------
    httpx.HTTPError
        If the API call fails (network, timeout, HTTP status).
    """
    period = f"{year_start}-{year_end}"
    resources: dict[str, DepartmentResource] = {}
    page = 1

    while True:
        response = client.get(
            _RESOURCES_API_URL,
            params={
                "q": f"periode_{period}",
                "page_size": _API_PAGE_SIZE,
                "page": page,
            },
        )
        response.raise_for_status()
        data = response.json()

        for res in data.get("data", []):
            title = res.get("title", "")
            match = _TITLE_RE.match(title)
            if not match:
                continue

            dept = match.group(1)
            res_period = f"{match.group(2)}-{match.group(3)}"
            if dept not in DEPARTMENTS or res_period != period:
                continue

            extras = res.get("extras", {}) or {}
            resources[dept] = {
                "dept": dept,
                "csv_url": res["url"],
                "parquet_url": extras.get("analysis:parsing:parquet_url"),
            }

        total = data.get("total", 0)
        if page * _API_PAGE_SIZE >= total:
            break
        page += 1

    with_parquet = sum(1 for r in resources.values() if r["parquet_url"])
    logger.info(
        "API discovery completed",
        departments_found=len(resources),
        with_parquet=with_parquet,
        period=period,
    )
    return resources


def _build_fallback_resources(
    *,
    year_start: int,
    year_end: int,
) -> dict[str, DepartmentResource]:
    """Build CSV.gz resource dict from hardcoded URL pattern.

    Used as the base for all downloads — API discovery enriches these entries with
    Parquet URLs where available. Parquet Hydra URLs use UUIDs and cannot be guessed
    without the API, so ``parquet_url`` is always ``None`` here.

    Parameters
    ----------
    year_start
        Start year of the period.
    year_end
        End year of the period.

    Returns
    -------
    dict[str, DepartmentResource]
        Mapping ``dept → resource`` with ``parquet_url`` always None.
    """
    return {
        dept: {
            "dept": dept,
            "csv_url": f"{_BASE_URL}/H_{dept}_latest-{year_start}-{year_end}.csv.gz",
            "parquet_url": None,
        }
        for dept in sorted(DEPARTMENTS)
    }


# --------------------------------------------------------------------------------------
# Per-department download
# --------------------------------------------------------------------------------------


def _stream_to_file(url: str, *, client: httpx.Client, path: Path) -> None:
    """Stream-download a URL to a local file.

    Parameters
    ----------
    url
        URL to download.
    client
        HTTP client.
    path
        Local file path to write.
    """
    with client.stream("GET", url) as response:
        response.raise_for_status()
        with path.open("wb") as f:
            for chunk in response.iter_bytes():
                f.write(chunk)


def _download_department(
    resource: DepartmentResource,
    *,
    client: httpx.Client,
    tmp_dir: Path,
) -> int:
    """Download a single department, preferring Parquet to CSV.gz.

    The downloaded data is normalized to all-Utf8 columns and written as a
    per-department Parquet file in ``tmp_dir``.

    Parameters
    ----------
    resource
        Department download URLs.
    client
        HTTP client.
    tmp_dir
        Temporary directory for intermediate files.

    Returns
    -------
    int
        Number of rows downloaded (0 if both downloads fail).
    """
    dept = resource["dept"]
    parquet_url = resource["parquet_url"]
    csv_url = resource["csv_url"]

    df: pl.DataFrame | None = None

    # Try Parquet (Hydra) first — ~20x smaller than CSV.gz
    if parquet_url:
        tmp_path = tmp_dir / f"{dept}_hydra.parquet"
        try:
            _stream_to_file(parquet_url, client=client, path=tmp_path)
            # Column projection: 196 → 16 columns at read time
            df = pl.read_parquet(tmp_path, columns=_LANDING_COLUMNS)
            # Cast to Utf8 for uniform schema across departments
            df = df.cast({c: pl.Utf8 for c in df.columns})
            logger.debug("Downloaded Parquet (Hydra)", department=dept, rows_count=len(df))
        except (httpx.HTTPError, pl.exceptions.PolarsError, OSError) as err:
            logger.warning(
                "Parquet download failed, falling back to CSV.gz",
                department=dept,
                error=str(err),
                error_type=type(err).__qualname__,
            )
            df = None
        finally:
            tmp_path.unlink(missing_ok=True)

    # Fallback to CSV.gz
    if df is None:
        tmp_path = tmp_dir / f"{dept}.csv.gz"
        try:
            _stream_to_file(csv_url, client=client, path=tmp_path)
            # Column projection + infer_schema=False → 16 Utf8 columns
            df = pl.read_csv(tmp_path, separator=";", infer_schema=False, columns=_LANDING_COLUMNS)
            logger.debug("Downloaded CSV.gz", department=dept, rows_count=len(df))
        except (httpx.HTTPError, pl.exceptions.PolarsError, OSError) as err:
            logger.warning(
                "Failed to download department",
                department=dept,
                url=csv_url,
                error=str(err),
                error_type=type(err).__qualname__,
            )
            return 0
        finally:
            tmp_path.unlink(missing_ok=True)

    out_path = tmp_dir / f"{dept}.parquet"
    df.write_parquet(out_path)
    return len(df)


# --------------------------------------------------------------------------------------
# Parallel download orchestration
# --------------------------------------------------------------------------------------


@dataclass(frozen=True, slots=True, kw_only=True)
class _BatchResult:
    """Aggregated result of the parallel department download."""

    dept_count: int
    failed_count: int
    total_rows: int


def _download_all_departments(
    resources: dict[str, DepartmentResource],
    *,
    client: httpx.Client,
    tmp_dir: Path,
    progress: BatchProgressFactory | None = None,
) -> _BatchResult:
    """Download all departments in parallel with progress tracking.

    Parameters
    ----------
    resources
        Mapping ``dept → DepartmentResource`` with download URLs.
    client
        Thread-safe HTTP client with shared connection pool.
    tmp_dir
        Temporary directory for per-department Parquet files.
    progress
        Factory called with ``total_items`` that returns a progress reporter.
        Pass ``None`` (default) to use the built-in tqdm progress bar.

    Returns
    -------
    _BatchResult
        Aggregated counts of successful, failed, and total rows.
    """
    dept_count = 0
    failed_count = 0
    total_rows = 0

    with ThreadPoolExecutor(max_workers=_DOWNLOAD_MAX_WORKERS) as pool:
        futures = {
            pool.submit(_download_department, resource, client=client, tmp_dir=tmp_dir): resource
            for resource in resources.values()
        }

        reporter: DownloadProgressReporter = (
            progress(len(futures))
            if progress is not None
            else tqdm(
                total=len(futures),
                unit="dept",
                desc="Downloading departments",
                file=sys.stderr,
                leave=False,
            )
        )

        try:
            for future in as_completed(futures):
                resource = futures[future]
                try:
                    rows = future.result()
                except (pl.exceptions.PolarsError, OSError):
                    logger.exception(
                        "Department download failed unexpectedly",
                        department=resource["dept"],
                    )
                    rows = 0
                if rows > 0:
                    dept_count += 1
                    total_rows += rows
                else:
                    failed_count += 1
                reporter.update(1)
        finally:
            reporter.close()

    return _BatchResult(dept_count=dept_count, failed_count=failed_count, total_rows=total_rows)


# --------------------------------------------------------------------------------------
# Main entry point
# --------------------------------------------------------------------------------------


def download_climatologie(
    dest_dir: Path,
    progress: BatchProgressFactory | None = None,
    *,
    year_start: int | None = None,
    year_end: int | None = None,
) -> Path:
    """Download all departmental data and merge into a single Parquet.

    Starts from a base of hardcoded CSV.gz URLs for all 95 departments, then enriches
    with Parquet Hydra URLs discovered via the data.gouv.fr API.
    Each department is downloaded independently: Parquet if available, CSV.gz otherwise.
    If the API is unreachable, all departments use CSV.gz.

    Parameters
    ----------
    dest_dir
        Landing directory to write the merged parquet file.
    progress
        Factory called with ``total_items`` that returns a progress reporter.
        Pass ``None`` (default) to use the built-in tqdm progress bar.
    year_start
        Start year for the 2-year window. Defaults to ``current_year - 1``.
    year_end
        End year for the 2-year window. Defaults to ``current_year``.

    Returns
    -------
    Path
        Path to the merged parquet file.

    Raises
    ------
    DownloadStageError
        If no data could be downloaded from any department.
    """
    now = datetime.now(tz=UTC)
    if year_start is None:
        year_start = now.year - 1
    if year_end is None:
        year_end = now.year

    # -- Initialize directories and HTTP client ----------------------------------------

    dest_dir.mkdir(parents=True, exist_ok=True)

    tmp_dir = dest_dir / "_tmp_departments"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    timeout = httpx.Timeout(timeout=settings.download_timeout_seconds)

    # -- Build resource list (fallback + API discovery) --------------------------------

    with httpx.Client(timeout=timeout, follow_redirects=True) as client:
        # Base: CSV.gz for all 95 departments (always works, no API needed)
        resources_by_dept = _build_fallback_resources(year_start=year_start, year_end=year_end)

        # Enrich with API discovery (adds Parquet URLs where available)
        try:
            api_resources = _fetch_department_resources(
                client=client, year_start=year_start, year_end=year_end
            )
            resources_by_dept.update(api_resources)
        except httpx.HTTPError as err:
            logger.warning("API discovery failed, using hardcoded CSV URLs only", error=str(err))

        # httpx.Client is thread-safe — parallel downloads with shared connection pool
        result = _download_all_departments(
            resources_by_dept, client=client, tmp_dir=tmp_dir, progress=progress
        )

    # -- Merge temporary parquets into final file --------------------------------------

    if result.dept_count == 0:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        raise DownloadStageError("No climatologie data downloaded from any department")

    # Lazy scan all temporary parquets and write the merged result.
    # This avoids loading all departments into memory simultaneously.
    merged_path = dest_dir / _MERGED_FILENAME
    try:
        lazy_frames = pl.scan_parquet(tmp_dir / "*.parquet")
        lazy_frames.sink_parquet(merged_path)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    log_kwargs: dict[str, object] = {
        "departments_count": result.dept_count,
        "rows_count": result.total_rows,
    }
    if result.failed_count > 0:
        log_kwargs["failed_count"] = result.failed_count
        logger.warning("Climatologie merge completed with failures", **log_kwargs)
    else:
        logger.info("Climatologie merge completed", **log_kwargs)

    return merged_path
