INSERT INTO {schema}.{table} (
    code_insee_region, date_heure, libelle_region, nature, date, heure,
    consommation, thermique, nucleaire, eolien, solaire, hydraulique,
    pompage, bioenergies, ech_physiques, stockage_batterie, destockage_batterie,
    tco_thermique, tch_thermique, tco_nucleaire, tch_nucleaire,
    tco_eolien, tch_eolien, tco_solaire, tch_solaire,
    tco_hydraulique, tch_hydraulique, tco_bioenergies, tch_bioenergies,
    inserted_at
)
SELECT
    code_insee_region, date_heure, libelle_region, nature, date, heure,
    consommation, thermique, nucleaire, eolien, solaire, hydraulique,
    pompage, bioenergies, ech_physiques, stockage_batterie, destockage_batterie,
    tco_thermique, tch_thermique, tco_nucleaire, tch_nucleaire,
    tco_eolien, tch_eolien, tco_solaire, tch_solaire,
    tco_hydraulique, tch_hydraulique, tco_bioenergies, tch_bioenergies,
    NOW()
FROM {staging}
ON CONFLICT (code_insee_region, date_heure) DO UPDATE SET
    libelle_region      = EXCLUDED.libelle_region,
    nature              = EXCLUDED.nature,
    date                = EXCLUDED.date,
    heure               = EXCLUDED.heure,
    consommation        = EXCLUDED.consommation,
    thermique           = EXCLUDED.thermique,
    nucleaire           = EXCLUDED.nucleaire,
    eolien              = EXCLUDED.eolien,
    solaire             = EXCLUDED.solaire,
    hydraulique         = EXCLUDED.hydraulique,
    pompage             = EXCLUDED.pompage,
    bioenergies         = EXCLUDED.bioenergies,
    ech_physiques       = EXCLUDED.ech_physiques,
    stockage_batterie   = EXCLUDED.stockage_batterie,
    destockage_batterie = EXCLUDED.destockage_batterie,
    tco_thermique       = EXCLUDED.tco_thermique,
    tch_thermique       = EXCLUDED.tch_thermique,
    tco_nucleaire       = EXCLUDED.tco_nucleaire,
    tch_nucleaire       = EXCLUDED.tch_nucleaire,
    tco_eolien          = EXCLUDED.tco_eolien,
    tch_eolien          = EXCLUDED.tch_eolien,
    tco_solaire         = EXCLUDED.tco_solaire,
    tch_solaire         = EXCLUDED.tch_solaire,
    tco_hydraulique     = EXCLUDED.tco_hydraulique,
    tch_hydraulique     = EXCLUDED.tch_hydraulique,
    tco_bioenergies     = EXCLUDED.tco_bioenergies,
    tch_bioenergies     = EXCLUDED.tch_bioenergies,
    updated_at          = NOW()
WHERE (
    {schema}.{table}.libelle_region,
    {schema}.{table}.nature,
    {schema}.{table}.date,
    {schema}.{table}.heure,
    {schema}.{table}.consommation,
    {schema}.{table}.thermique,
    {schema}.{table}.nucleaire,
    {schema}.{table}.eolien,
    {schema}.{table}.solaire,
    {schema}.{table}.hydraulique,
    {schema}.{table}.pompage,
    {schema}.{table}.bioenergies,
    {schema}.{table}.ech_physiques,
    {schema}.{table}.stockage_batterie,
    {schema}.{table}.destockage_batterie,
    {schema}.{table}.tco_thermique,
    {schema}.{table}.tch_thermique,
    {schema}.{table}.tco_nucleaire,
    {schema}.{table}.tch_nucleaire,
    {schema}.{table}.tco_eolien,
    {schema}.{table}.tch_eolien,
    {schema}.{table}.tco_solaire,
    {schema}.{table}.tch_solaire,
    {schema}.{table}.tco_hydraulique,
    {schema}.{table}.tch_hydraulique,
    {schema}.{table}.tco_bioenergies,
    {schema}.{table}.tch_bioenergies
) IS DISTINCT FROM (
    EXCLUDED.libelle_region,
    EXCLUDED.nature,
    EXCLUDED.date,
    EXCLUDED.heure,
    EXCLUDED.consommation,
    EXCLUDED.thermique,
    EXCLUDED.nucleaire,
    EXCLUDED.eolien,
    EXCLUDED.solaire,
    EXCLUDED.hydraulique,
    EXCLUDED.pompage,
    EXCLUDED.bioenergies,
    EXCLUDED.ech_physiques,
    EXCLUDED.stockage_batterie,
    EXCLUDED.destockage_batterie,
    EXCLUDED.tco_thermique,
    EXCLUDED.tch_thermique,
    EXCLUDED.tco_nucleaire,
    EXCLUDED.tch_nucleaire,
    EXCLUDED.tco_eolien,
    EXCLUDED.tch_eolien,
    EXCLUDED.tco_solaire,
    EXCLUDED.tch_solaire,
    EXCLUDED.tco_hydraulique,
    EXCLUDED.tch_hydraulique,
    EXCLUDED.tco_bioenergies,
    EXCLUDED.tch_bioenergies
);
